#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleSample.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ScheduleData")]
	public partial class ScheduleDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertResourceTable(ResourceTable instance);
    partial void UpdateResourceTable(ResourceTable instance);
    partial void DeleteResourceTable(ResourceTable instance);
    partial void InsertScheduleEventData(ScheduleEventData instance);
    partial void UpdateScheduleEventData(ScheduleEventData instance);
    partial void DeleteScheduleEventData(ScheduleEventData instance);
    partial void InsertEmployeeTable(EmployeeTable instance);
    partial void UpdateEmployeeTable(EmployeeTable instance);
    partial void DeleteEmployeeTable(EmployeeTable instance);
    #endregion
		
		public ScheduleDataDataContext() : 
				base(global::ScheduleSample.Properties.Settings.Default.ScheduleDataConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ResourceTable> ResourceTables
		{
			get
			{
				return this.GetTable<ResourceTable>();
			}
		}
		
		public System.Data.Linq.Table<ScheduleEventData> ScheduleEventDatas
		{
			get
			{
				return this.GetTable<ScheduleEventData>();
			}
		}
		
		public System.Data.Linq.Table<EmployeeTable> EmployeeTables
		{
			get
			{
				return this.GetTable<EmployeeTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ResourceTable")]
	public partial class ResourceTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AirlineId;
		
		private string _AirlineName;
		
		private string _AirlineColor;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAirlineIdChanging(string value);
    partial void OnAirlineIdChanged();
    partial void OnAirlineNameChanging(string value);
    partial void OnAirlineNameChanged();
    partial void OnAirlineColorChanging(string value);
    partial void OnAirlineColorChanged();
    #endregion
		
		public ResourceTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirlineId", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AirlineId
		{
			get
			{
				return this._AirlineId;
			}
			set
			{
				if ((this._AirlineId != value))
				{
					this.OnAirlineIdChanging(value);
					this.SendPropertyChanging();
					this._AirlineId = value;
					this.SendPropertyChanged("AirlineId");
					this.OnAirlineIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirlineName", DbType="NVarChar(MAX)")]
		public string AirlineName
		{
			get
			{
				return this._AirlineName;
			}
			set
			{
				if ((this._AirlineName != value))
				{
					this.OnAirlineNameChanging(value);
					this.SendPropertyChanging();
					this._AirlineName = value;
					this.SendPropertyChanged("AirlineName");
					this.OnAirlineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirlineColor", DbType="NVarChar(MAX)")]
		public string AirlineColor
		{
			get
			{
				return this._AirlineColor;
			}
			set
			{
				if ((this._AirlineColor != value))
				{
					this.OnAirlineColorChanging(value);
					this.SendPropertyChanging();
					this._AirlineColor = value;
					this.SendPropertyChanged("AirlineColor");
					this.OnAirlineColorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ScheduleEventData")]
	public partial class ScheduleEventData : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Subject;
		
		private System.Nullable<System.DateTime> _StartTime;
		
		private System.Nullable<System.DateTime> _EndTime;
		
		private string _StartTimezone;
		
		private string _EndTimezone;
		
		private System.Nullable<bool> _IsAllDay;
		
		private string _RecurrenceRule;
		
		private System.Nullable<int> _RecurrenceID;
		
		private string _RecurrenceException;
		
		private string _AirlineId;
		
		private string _PilotId;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSubjectChanging(string value);
    partial void OnSubjectChanged();
    partial void OnStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnStartTimeChanged();
    partial void OnEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnEndTimeChanged();
    partial void OnStartTimezoneChanging(string value);
    partial void OnStartTimezoneChanged();
    partial void OnEndTimezoneChanging(string value);
    partial void OnEndTimezoneChanged();
    partial void OnIsAllDayChanging(System.Nullable<bool> value);
    partial void OnIsAllDayChanged();
    partial void OnRecurrenceRuleChanging(string value);
    partial void OnRecurrenceRuleChanged();
    partial void OnRecurrenceIDChanging(System.Nullable<int> value);
    partial void OnRecurrenceIDChanged();
    partial void OnRecurrenceExceptionChanging(string value);
    partial void OnRecurrenceExceptionChanged();
    partial void OnAirlineIdChanging(string value);
    partial void OnAirlineIdChanged();
    partial void OnPilotIdChanging(string value);
    partial void OnPilotIdChanged();
    #endregion
		
		public ScheduleEventData()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subject", DbType="NVarChar(MAX)")]
		public string Subject
		{
			get
			{
				return this._Subject;
			}
			set
			{
				if ((this._Subject != value))
				{
					this.OnSubjectChanging(value);
					this.SendPropertyChanging();
					this._Subject = value;
					this.SendPropertyChanged("Subject");
					this.OnSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartTime
		{
			get
			{
				return this._StartTime;
			}
			set
			{
				if ((this._StartTime != value))
				{
					this.OnStartTimeChanging(value);
					this.SendPropertyChanging();
					this._StartTime = value;
					this.SendPropertyChanged("StartTime");
					this.OnStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndTime
		{
			get
			{
				return this._EndTime;
			}
			set
			{
				if ((this._EndTime != value))
				{
					this.OnEndTimeChanging(value);
					this.SendPropertyChanging();
					this._EndTime = value;
					this.SendPropertyChanged("EndTime");
					this.OnEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartTimezone", DbType="NVarChar(MAX)")]
		public string StartTimezone
		{
			get
			{
				return this._StartTimezone;
			}
			set
			{
				if ((this._StartTimezone != value))
				{
					this.OnStartTimezoneChanging(value);
					this.SendPropertyChanging();
					this._StartTimezone = value;
					this.SendPropertyChanged("StartTimezone");
					this.OnStartTimezoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndTimezone", DbType="NVarChar(MAX)")]
		public string EndTimezone
		{
			get
			{
				return this._EndTimezone;
			}
			set
			{
				if ((this._EndTimezone != value))
				{
					this.OnEndTimezoneChanging(value);
					this.SendPropertyChanging();
					this._EndTimezone = value;
					this.SendPropertyChanged("EndTimezone");
					this.OnEndTimezoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAllDay", DbType="Bit")]
		public System.Nullable<bool> IsAllDay
		{
			get
			{
				return this._IsAllDay;
			}
			set
			{
				if ((this._IsAllDay != value))
				{
					this.OnIsAllDayChanging(value);
					this.SendPropertyChanging();
					this._IsAllDay = value;
					this.SendPropertyChanged("IsAllDay");
					this.OnIsAllDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurrenceRule", DbType="NVarChar(MAX)")]
		public string RecurrenceRule
		{
			get
			{
				return this._RecurrenceRule;
			}
			set
			{
				if ((this._RecurrenceRule != value))
				{
					this.OnRecurrenceRuleChanging(value);
					this.SendPropertyChanging();
					this._RecurrenceRule = value;
					this.SendPropertyChanged("RecurrenceRule");
					this.OnRecurrenceRuleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurrenceID", DbType="Int")]
		public System.Nullable<int> RecurrenceID
		{
			get
			{
				return this._RecurrenceID;
			}
			set
			{
				if ((this._RecurrenceID != value))
				{
					this.OnRecurrenceIDChanging(value);
					this.SendPropertyChanging();
					this._RecurrenceID = value;
					this.SendPropertyChanged("RecurrenceID");
					this.OnRecurrenceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecurrenceException", DbType="NVarChar(MAX)")]
		public string RecurrenceException
		{
			get
			{
				return this._RecurrenceException;
			}
			set
			{
				if ((this._RecurrenceException != value))
				{
					this.OnRecurrenceExceptionChanging(value);
					this.SendPropertyChanging();
					this._RecurrenceException = value;
					this.SendPropertyChanged("RecurrenceException");
					this.OnRecurrenceExceptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AirlineId", DbType="NVarChar(50)")]
		public string AirlineId
		{
			get
			{
				return this._AirlineId;
			}
			set
			{
				if ((this._AirlineId != value))
				{
					this.OnAirlineIdChanging(value);
					this.SendPropertyChanging();
					this._AirlineId = value;
					this.SendPropertyChanged("AirlineId");
					this.OnAirlineIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PilotId", DbType="NVarChar(50)")]
		public string PilotId
		{
			get
			{
				return this._PilotId;
			}
			set
			{
				if ((this._PilotId != value))
				{
					this.OnPilotIdChanging(value);
					this.SendPropertyChanging();
					this._PilotId = value;
					this.SendPropertyChanged("PilotId");
					this.OnPilotIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.EmployeeTable")]
	public partial class EmployeeTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PilotId;
		
		private string _groupId;
		
		private string _text;
		
		private string _color;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPilotIdChanging(string value);
    partial void OnPilotIdChanged();
    partial void OngroupIdChanging(string value);
    partial void OngroupIdChanged();
    partial void OntextChanging(string value);
    partial void OntextChanged();
    partial void OncolorChanging(string value);
    partial void OncolorChanged();
    #endregion
		
		public EmployeeTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PilotId", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PilotId
		{
			get
			{
				return this._PilotId;
			}
			set
			{
				if ((this._PilotId != value))
				{
					this.OnPilotIdChanging(value);
					this.SendPropertyChanging();
					this._PilotId = value;
					this.SendPropertyChanged("PilotId");
					this.OnPilotIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupId", DbType="NVarChar(1)")]
		public string groupId
		{
			get
			{
				return this._groupId;
			}
			set
			{
				if ((this._groupId != value))
				{
					this.OngroupIdChanging(value);
					this.SendPropertyChanging();
					this._groupId = value;
					this.SendPropertyChanged("groupId");
					this.OngroupIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_text", DbType="NVarChar(MAX)")]
		public string text
		{
			get
			{
				return this._text;
			}
			set
			{
				if ((this._text != value))
				{
					this.OntextChanging(value);
					this.SendPropertyChanging();
					this._text = value;
					this.SendPropertyChanged("text");
					this.OntextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_color", DbType="NChar(10)")]
		public string color
		{
			get
			{
				return this._color;
			}
			set
			{
				if ((this._color != value))
				{
					this.OncolorChanging(value);
					this.SendPropertyChanging();
					this._color = value;
					this.SendPropertyChanged("color");
					this.OncolorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
